apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/ethiebaut/config-image:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/ethiebaut/config-image:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: config-image
        chartPath: charts/config-image
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/ethiebaut/config-image"
          image.tag: "{{.DIGEST_HEX}}"
